function phi = ModeShape(x, beta, ...
        Pm_1, Qm_1, Rm_1, Sm_1, tau, epsilon, psi)
    % Define input argument
    betaX = beta * x;
    % Define the mode shape, phi(x)
    phi = (tau/2) ...
        .* ( psi^0*Pm_1*(cosh(betaX)+cos(betaX)) ...
           + psi^1*Qm_1*(sinh(betaX)+sin(betaX)) ...
           + psi^2*epsilon*Rm_1*(cosh(betaX)-cos(betaX)) ...
           + psi^3*epsilon*Sm_1*(sinh(betaX)-sin(betaX)));
end
