function d3phi_dx3 = Phi_3rd_Deriv(x, beta, ...
        Pm_1, Qm_1, Rm_1, Sm_1, tau, epsilon, psi)
    % Define input argument
    betaX = beta * x;
    % Define the 3rd derivative of the mode shape, phi'''(x)
    d3phi_dx3 = (tau/2) * beta.^3 ...
        .* ( psi^0*Pm_1*(sinh(betaX)+sin(betaX)) ...
           + psi^1*Qm_1*(cosh(betaX)-cos(betaX)) ...
           + psi^2*epsilon*Rm_1*(sinh(betaX)-sin(betaX))...
           + psi^3*epsilon*Sm_1*(cosh(betaX)+cos(betaX)));
end
