function dphi_dx = Phi_1st_Deriv(x, beta, ...
        Pm_1, Qm_1, Rm_1, Sm_1, tau, epsilon, psi)
    % Define input argument
    betaX = beta * x;
    % Define the 1st derivative of the mode shape, phi'(x)
    dphi_dx = (tau/2) * beta ...
        .* ( psi^0*Pm_1*(sinh(betaX)-sin(betaX)) ...
           + psi^1*Qm_1*(cosh(betaX)+cos(betaX)) ...
           + psi^2*epsilon*Rm_1*(sinh(betaX)+sin(betaX))...
           + psi^3*epsilon*Sm_1*(cosh(betaX)-cos(betaX)));
end
